app:
  name: springboot-jwt-demo

jwt:
  header: Authorization
  expires_in: 300 # 5 minutes
  mobile_expires_in: 600 # 10 minutes
  secret: queenvictoria
  
spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/rabbitcoffee
    username: fx
    password: root
    driver-class-name: org.postgresql.Driver